# Generated by Django 3.2.9 on 2021-11-24 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('row', '0001_initial'),
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.rank')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='row.row')),
            ],
            options={
                'unique_together': {('row', 'number')},
            },
        ),
    ]
