version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - web_network
    restart: always
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    restart: always
    networks:
      - web_network

  redis:
    image: "redis:alpine"
    networks:
      - web_network
    ports:
      - "6379:6379"
  celery:
    build: .
    restart: always
    command: celery -A theater_seating worker -c 4 -B -l debug
    volumes:
      - .:/code
    depends_on:
      - db
      - web
      - redis
    networks:
      - web_network

networks:
  web_network:
    driver: bridge