# Generated by Django 3.2.9 on 2021-11-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('hall', 'name')},
        ),
        migrations.RemoveField(
            model_name='section',
            name='position',
        ),
    ]
