# Generated by Django 3.2.9 on 2021-11-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_auto_20211124_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
