# Generated by Django 3.2.9 on 2021-11-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0005_alter_section_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='is_curve',
            new_name='is_left_curve',
        ),
        migrations.AddField(
            model_name='section',
            name='is_middle_curve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='is_right_curve',
            field=models.BooleanField(default=False),
        ),
    ]
