# Generated by Django 3.2.9 on 2021-11-25 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='color',
            field=models.CharField(default='gray', max_length=16),
        ),
        migrations.AddField(
            model_name='rank',
            name='price',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=9, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
