# Generated by Django 3.2.9 on 2021-12-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0004_alter_rank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='color',
            field=models.CharField(db_index=True, default='gray', max_length=16),
        ),
    ]
