# Generated by Django 3.2.9 on 2021-11-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('row', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='number',
            field=models.IntegerField(),
        ),
    ]
