# Generated by Django 3.2.9 on 2021-11-24 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0001_initial'),
        ('row', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.section'),
        ),
        migrations.AlterUniqueTogether(
            name='row',
            unique_together={('section', 'number')},
        ),
    ]
