# Generated by Django 3.2.9 on 2021-11-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
        ('row', '0002_alter_row_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='position',
            field=models.IntegerField(choices=[(0, 'Middle'), (1, 'Left'), (2, 'Right')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='row',
            unique_together={('section', 'number', 'position')},
        ),
    ]
