# Generated by Django 2.1.7 on 2021-11-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('row', '0003_auto_20211124_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
