# Generated by Django 3.2.9 on 2021-12-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('row', '0005_alter_row_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='number',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='row',
            name='position',
            field=models.IntegerField(choices=[(0, 'Middle'), (1, 'Left'), (2, 'Right')], db_index=True, default=0),
        ),
    ]
