# Generated by Django 3.2.9 on 2021-11-24 16:28

import django.core.validators
from django.db import migrations, models
import user.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(db_index=True, max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator(message='your phone number is incorrect', regex='^09\\d{9}$')], verbose_name='phone number')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='user_data/profile_picture/')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Regular'), (2, 'Admin')], default=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male')], null=True)),
                ('one_time_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='one time password')),
                ('one_time_password_creation_date', models.DateTimeField(blank=True, null=True, verbose_name='one time password creation date')),
                ('is_banned', models.BooleanField(default=False, verbose_name='is banned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', user.manager.UserManager()),
            ],
        ),
    ]
