# Generated by Django 3.2.9 on 2021-11-24 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator(message='your phone number is incorrect', regex='^09\\d{9}$')], verbose_name='phone number'),
        ),
    ]
