# Generated by Django 3.2.9 on 2021-11-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_alter_hall_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
