# Generated by Django 3.2.9 on 2021-11-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0004_auto_20211130_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='img',
            field=models.ImageField(null=True, upload_to='static/uploads/img/'),
        ),
    ]
