# Generated by Django 2.1.7 on 2021-11-26 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0002_auto_20211126_1506'),
        ('seat', '0002_auto_20211126_1506'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('user', 'seance', 'seat')},
        ),
    ]
