# Generated by Django 2.1.7 on 2021-11-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0002_auto_20211126_1506'),
        ('seance', '0002_auto_20211126_1506'),
        ('ticket', '0002_auto_20211126_1506'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('seance', 'seat')},
        ),
    ]
