# Generated by Django 3.2.9 on 2021-11-30 06:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ticket',
            managers=[
                ('available_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
